// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package list

type UintList struct {
	list []uint
}

func NewUintList() *UintList {
	return &UintList{list: []uint{}}
}

func (l *UintList) Add(v uint) {
	l.list = append(l.list, v)
}

func (l *UintList) Get() uint {
	r := l.list[0]
	l.list = l.list[1:]
	return r
}
