package main

import (
	"./list"
	"fmt"
)

func main() {
	// Create a unit List
	// Note that this struct and related methods are autogenerated
	ul := list.NewUintList()

	// insert 1
	ul.Add(1)

	// ensure we get it back!
	fmt.Println(ul.Get())
}
